server:
  port: 8080

jwt:
  secret: sdsdg734fsjhfuseyfgsgdfgdfgdfg345;4l35k34;lk53;4lk5
  access-expiration-time: 3600000
  refresh-expiration-time: 604800000

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  level:
    org.springframework.security: info
    org.springframework.security.web.FilterChainProxy: debug
    org.springframework.security.web.org.springframework.security.web.authentication: trace
    root: info

spring:
  application:
    name: ${APPLICATION_NAME:auth-service}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 10
        enable.idempotence: true
    topics:
      mailing: mailing

grpc:
  client:
    user-service:
      address: "discovery:///user-service"
      negotiation-type: plaintext

app:
  public-url: https://auth-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: ${EUREKA_HOST_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always