server:
  port: 8080

jwt:
  secret: sdsdg734fsjhfuseyfgsgdfgdfgdfg345;4l35k34;lk53;4lk5
  access-expiration-time: 3600000
  refresh-expiration-time: 604800000

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  level:
    org.springframework.security: info
    org.springframework.security.web.FilterChainProxy: debug
    org.springframework.security.web.org.springframework.security.web.authentication: trace
    root: info

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST_URL:http://localhost:8761/eureka}