package com.auth_service.enums;

public enum ErrorCode {

    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_EMAIL_CONFIRMATION_TOKEN_EXPIRED("USER_EMAIL_CONFIRMATION_TOKEN_EXPIRED"),
    EMAIL_ALREADY_ACTIVATED("EMAIL_ALREADY_ACTIVATED"),
    EMAIL_ALREADY_EXIST("EMAIL_ALREADY_EXIST"),
    USERNAME_ALREADY_EXIST("USERNAME_ALREADY_EXIST"),
    EMAIL_NOT_FOUND("EMAIL_NOT_FOUND"),
    USER_EMAIL_CONFIRMATION_NOT_FOUND("USER_EMAIL_CONFIRMATION_NOT_FOUND"),
    USER_CREDENTIALS_CONFLICT("USER_CREDENTIALS_CONFLICT"),
    USER_SERVICE_UNEXPECTED_ERROR("USER_SERVICE_UNEXPECTED_ERROR"),
    INVALID_REFRESH_TOKEN("INVALID_REFRESH_TOKEN");


    ErrorCode(String name) {
    }
}
