package com.auth_service.enums;

public enum ExceptionStatus {

    USER_NOT_FOUND("USER_NOT_FOUND"),
    EMAIL_IS_ALREADY_ACTIVATED("EMAIL_IS_ALREADY_ACTIVATED"),
    EMAIL_IS_ALREADY_EXIST("EMAIL_IS_ALREADY_EXIST"),
    EMAIL_NOT_FOUND("EMAIL_NOT_FOUND"),
    USERNAME_IS_ALREADY_EXIST("USERNAME_IS_ALREADY_EXIST"),
    USER_EMAIL_CONFIRMATION_NOT_FOUND("USER_EMAIL_CONFIRMATION_NOT_FOUND"),
    USER_CREDENTIALS_CONFLICT("USER_CREDENTIALS_CONFLICT"),
    INVALID_REFRESH_TOKEN("INVALID_REFRESH_TOKEN"),

    USER_SERVICE_UNEXPECTED_ERROR("USER_SERVICE_UNEXPECTED_ERROR"),

    USER_EMAIL_CONFIRMATION_TOKEN_EXPIRED("USER_EMAIL_CONFIRMATION_TOKEN_EXPIRED");

    ExceptionStatus(String name) {
    }
}
